version: "3"

volumes:
  mongodb_volume:

services:
  mongodb:
    image: mongo:latest
    volumes:
    - mongodb_volume:/data/db
    restart: always

  web_service:
    restart: always
    build: .
    ports:
    - 8080:8080
    environment:
    - MONGO_HOST = '*'
